=== cessda/cessda.cdc.osmh-indexer.cmm/src/main/resources/json/schema/CMMStudy.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$defs":  {
    "vocabAttributes": {
      "type": "object",
      "description": "A term in a controlled vocabulary.",
      "properties": {
        "vocab": {
          "type": "string",
          "description": "The name of the controlled vocabulary."
        },
        "vocabUri": {
          "type": "string",
          "description": "The URI of the controlled vocabulary."
        },
        "id": {
          "type": "string",
          "description": "The ID of the item in the controlled vocabulary."
        },
        "term": {
          "type": "string",
          "description": "The term being referenced."
        }
      },
      "additionalProperties": false
    }
  },
  "title": "CMMStudy",
  "description": "This schema defines the format of the CMMStudy record type.",
  "type": "object",
  "required": [
    "studyNumber"
  ],
  "additionalProperties": false,
  "properties": {
    "abstract": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy abstract for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing an abstract in various languages. Uses language code properties and abstract values. E.g. {'en': 'An abstract', 'no': 'Et sammendrag'}"
    },
    "accessClass": {
      "type": "string",
      "description": "Class of availability of the research data."
    },
    "associatedInstitutions": {
      "type": "array",
      "description": "An array of Associated Institutions for this CMMStudy.",
      "items": {
        "type": "string",
        "description": "A CMMStudy Associated Institution ."
      }
    },
    "classIdentifier": {
      "type": "string",
      "description": "Unique identifier of class/category within the classification system."
    },
    "classifications": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Topics(classifications) for this CMMStudy in potentially multiple languages."
    },
    "code": {
      "type": "string",
      "description": "The short name of the repository as defined in the CESSDA Vocabularies Service."
    },
    "creators": {
      "type": "object",
      "description": "A Collection of Creators(affiliation) eg \"Ami Doe(University of DV)\". Potentially in many translated languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A Collection of Creators(affiliation) translated in this language",
          "items": [
            {
              "type": "object",
              "description": "A Creator instance.",
              "properties": {
                "name": {
                  "type": "string"
                },
                "affiliation": {
                  "type": "string"
                },
                "identifiers": {
                  "type": "array",
                  "description": "A collection of unique identifiers for a creator (e.g. ORCID)",
                  "items": [
                    {
                      "type": "object",
                      "description": "A unique identifier for a creator (e.g. ORCID, ROR etc.)",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "uri": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  ],
                  "additionalProperties": false
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccess": {
      "type": "string",
      "description": "Data Access preferably as Open or Restricted, either according to CV values or mapped from free text values. Will be Uncategorized if it would be empty otherwise."
    },
    "dataAccessFreeTexts": {
      "type": "object",
      "description": "A Collection of Data Access Free Texts descriptions for data collection, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "string",
              "description": "A Data Access Free Texts description for data collection.",
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccessUrl": {
      "type": "object",
      "description": "A URL where a user can navigate to access the data behind this study.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string"
        }
      }
    },
    "dataCollectionFreeTexts": {
      "type": "object",
      "description": "A collection of data collection FreeTexts Dates, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A collection data collection FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A data Collection FreeTexts instance",
              "properties": {
                "dataCollectionFreeText": {
                  "type": "string"
                },
                "event": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataCollectionPeriodEnddate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionPeriodStartdate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionYear": {
      "type": "integer",
      "description": "A JSON date year string, e.g. 2012."
    },
    "dataKindFreeTexts": {
      "type": "object",
      "description": "A collection of Data Kind FreeTexts, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection Data Kind FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A Data Kind FreeTexts instance",
              "properties": {
                "dataKindFreeText": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "fileLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A CMMStudy File Language (standardised ISO)."
      },
      "description": "An array of File Languages (standardised ISO) for this CMMStudy."
    },
    "funding": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of funding formation for this CMMStudy in this given ISO language code",
          "items": [
            {
              "type": "object",
              "description": "CMMStudy Funding Information",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "grantNumber": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "generalDataFormats": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of General Data Formats for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "General Data Formats for this CMMStudy in potentially multiple languages."
    },
    "isActive": {
      "type": "boolean",
      "description": "Is the record marked as deleted. If record is deleted this = false.",
      "default": true
    },
    "keywords": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Keywords for this CMMStudy in this Given iso Language code",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy keyword.",
              "properties": {
                "vocab": {
                  "type": "string"
                },
                "vocabUri": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "term": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Keywords for this CMMStudy in potentially multiple languages."
    },
    "langAvailableIn": {
      "type": "array"
    },
    "lastModified": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z.",
      "format": "date-time"
    },
    "oaiIdentifier": {
      "type": "string",
      "description": "The OAI identifier that is returned by the OAI-PMH repository."
    },
    "pidStudies": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "An array of Persistent Identifiers for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Persistent Identifier.",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "pid": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Persistent Identifiers for this CMMStudy in potentially multiple languages."
    },
    "publicationYear": {
      "type": "string",
      "description": "Year of publication (by publisher) of the study (for citation) - [YYYY] or the whole [YYYY-MM-DD]."
    },
    "publisher": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A CMMStudy institution publishing the research data for the given language code.",
          "properties": {
            "abbr": {
              "type": "string"
            },
            "publisher": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "recordType": {
      "type": "string",
      "description": "The type of record, i.e.'CMMStudy'.",
      "enum": [
        "CMMStudy"
      ]
    },
    "relatedPublications": {
      "type": "object",
      "description": "Related publications to this study. This may be present in multiple languages.",
      "patternProperties": {
        "[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "A related publications object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "The title of the related publication"
                },
                "holdings": {
                  "type": "array",
                  "description": "The URIs of the holdings of the related publication.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    "repositoryUrl": {
      "type": "string",
      "description": "The URL of the repository as defined in the repository's configuration"
    },
    "series": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "Series / study group that the study belongs to.",
              "properties": {
                "names": {
                  "type": "array",
                  "description": "An array of names of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "descriptions": {
                  "type": "array",
                  "description": "An array of descriptions of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "uris": {
                  "type": "array",
                  "description": "An array of URIs to the series / study group description page in the SPs web page.",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "studyAreaCountries": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Countries for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Country.",
              "properties": {
                "abbr": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "searchField": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Countries for this CMMStudy in potentially multiple languages."
    },
    "studyNumber": {
      "type": "string",
      "description": "A studyNumber that uniquely identifies the CMMStudy within the datacatalogue."
    },
    "studyUrl": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "string",
          "description": "A CMMStudy study Url for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing CmmStudy Urls in various languages."
    },
    "studyXmlSourceUrl": {
      "type": "string",
      "description": "The Study's Full xml URL of the Service Provider's endpoint"
    },
    "titleStudy": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy studyTitle for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "typeOfModeOfCollections": {
      "type": "object",
      "description": "A collection of description of the methods of data collection in Potentially many languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection of description of methods for this given language",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfSamplingProcedures": {
      "type": "object",
      "description": "Sampling procedures used for data collection.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfTimeMethods": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of timeDimensions for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Time Methods for this CMMStudy in potentially multiple languages."
    },
    "unitTypes": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Analysis Units for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Analysis Units for this CMMStudy in potentially multiple languages."
    },
    "universe": {
      "type": "object",
      "description": "The universes that the study belongs to. This may be present in multiple languages.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A universe instance.",
          "properties": {
            "inclusion": {
              "description": "The included group of this universe.",
              "type": "string"
            },
            "exclusion": {
              "type": "string",
              "description": "The excluded group of this universe."
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
}

=== cessda/cessda.cdc.osmh-indexer.cmm/src/test/resources/json/ddi_record_1683_with_codebookXmlLag.json
{
  "studyNumber": "1683",
  "titleStudy": {
    "zz": "Machinery of Government, 1976-1977",
    "no": "Et Machinery of Government2, 1976-1977"
  },
  "abstract": {
    "zz": "<p>Abstract copyright UK Data Service and data collection copyright owner.</p>This\n                study contains a complete transcript of the Cornwall returns of the census of 1851.<br><B>Main Topics</B>:<br>Using microfiche loaned to the project by the LDS, volunteers, recruited online, transcribed the pages of the enumerators' books for the Cornwall 1851 census. Other volunteers checked the data using Free Census software. Finally, the organiser validated the data, using yet another piece of Free Census software.<br>\n                <br>\n                The original data was collected in 1851. the raw data was in the form of microfiche, organised in accordance with the PRO regulations"
  },
  "classifications": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "Government and political systems - Politics"
      },
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "Management and organisation - Industry and management"
      }
    ]
  },
  "keywords": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "1976"
      },
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "1977"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/9e7cc815-90cb-4f96-b8ff-a0a44ab25ea9",
        "id": "",
        "term": "BUDGETS"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/209e0ca3-1f3a-4034-b762-744692a9258c",
        "id": "",
        "term": "BUREAUCRACY"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/0a4ca3b1-1da3-4752-9074-e14ebbfa7dcd",
        "id": "",
        "term": "CENTRAL GOVERNMENT"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/0a9e181b-54f7-456e-911d-75e42dc52bbf",
        "id": "",
        "term": "CIVIL SERVICE"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/416c9ed0-a256-4aed-b81c-a1ab1ac8a2ac",
        "id": "",
        "term": "GOVERNMENT DEPARTMENTS"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/3a49ce91-4b6f-42ba-918b-07a3a55961f6",
        "id": "",
        "term": "GRANTS"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/af82c5dc-19be-4ad3-8f0a-612f314e1436",
        "id": "",
        "term": "GREAT BRITAIN"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/109136cf-0d85-40d0-96de-e2584bbc42ef",
        "id": "",
        "term": "OCCUPATIONS"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/d9893276-de95-4bef-a38d-95a85fdd67f5",
        "id": "",
        "term": "PERSONNEL"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/19754f6d-6c61-44e0-b406-b776712424a9",
        "id": "",
        "term": "PUBLIC EXPENDITURE"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/96c7c14b-f933-418f-81a0-29330e85acf7",
        "id": "",
        "term": "PURCHASING"
      },
      {
        "vocab": "",
        "vocabUri": "http://lod.data-archive.ac.uk/skoshasset/c00fd314-8751-4f9a-8862-6b9880f38148",
        "id": "",
        "term": "WAGES"
      }
    ]
  },
  "typeOfTimeMethods": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "Cross-sectional (one-time) study"
      }
    ]
  },
  "studyAreaCountries": {
  },
  "unitTypes": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "Institutions/organisations"
      }
    ]
  },
  "publisher": {
    "zz": {
      "abbr": "Publisher not specified",
      "publisher": "UK Data Service"
    }
  },
  "publicationYear": "1982-01-01T00:00:00Z",
  "pidStudies": {
    "*": [
      {
        "agency": "UKDA",
        "pid": "1683"
      },
      {
        "agency": "datacite",
        "pid": "10.5255/UKDA-SN-1683-1"
      }
    ]
  },
  "fileLanguages": [
    "en",
    "us"
  ],
  "creators": {
    "*": [
      {
        "name": "Hood, C.C., University of York. Institute of Social and Economic Research"
      },
      {
        "name": "Dunsire, A.",
        "affiliation": "institution"
      },
      {
        "name": "Thomson, K.S., University of York. Institute of Social and Economic Research"
      }
    ]
  },
  "typeOfSamplingProcedures": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "No sampling (total universe)"
      },
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "No sampling (total universe) TEST"
      }
    ]
  },
  "typeOfModeOfCollections": {
    "zz": [
      {
        "vocab": "",
        "vocabUri": "",
        "id": "",
        "term": "Compilation or synthesis of existing material"
      }
    ]
  },
  "dataCollectionPeriodStartdate": "1976-01-01T00:00:00Z",
  "dataCollectionFreeTexts": {},
  "dataAccess": "Restricted",
  "dataAccessFreeTexts": {
    "zz": [
      "The depositor has specified that registration is required and standard conditions of use apply. The depositor may be informed about usage. See <a href=http://ukdataservice.ac.uk/get-data/how-to-access/conditions.aspx>terms and conditions of access</a> for further information."
    ]
  },
  "lastModified": "2017-08-10T06:40:45Z"
}
