=== cessda/cessda.cdc.osmh-indexer.cmm/src/main/resources/json/schema/CMMStudy.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$defs":  {
    "vocabAttributes": {
      "type": "object",
      "description": "A term in a controlled vocabulary.",
      "properties": {
        "vocab": {
          "type": "string",
          "description": "The name of the controlled vocabulary."
        },
        "vocabUri": {
          "type": "string",
          "description": "The URI of the controlled vocabulary."
        },
        "id": {
          "type": "string",
          "description": "The ID of the item in the controlled vocabulary."
        },
        "term": {
          "type": "string",
          "description": "The term being referenced."
        }
      },
      "additionalProperties": false
    }
  },
  "title": "CMMStudy",
  "description": "This schema defines the format of the CMMStudy record type.",
  "type": "object",
  "required": [
    "studyNumber"
  ],
  "additionalProperties": false,
  "properties": {
    "abstract": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy abstract for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing an abstract in various languages. Uses language code properties and abstract values. E.g. {'en': 'An abstract', 'no': 'Et sammendrag'}"
    },
    "accessClass": {
      "type": "string",
      "description": "Class of availability of the research data."
    },
    "associatedInstitutions": {
      "type": "array",
      "description": "An array of Associated Institutions for this CMMStudy.",
      "items": {
        "type": "string",
        "description": "A CMMStudy Associated Institution ."
      }
    },
    "classIdentifier": {
      "type": "string",
      "description": "Unique identifier of class/category within the classification system."
    },
    "classifications": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Topics(classifications) for this CMMStudy in potentially multiple languages."
    },
    "code": {
      "type": "string",
      "description": "The short name of the repository as defined in the CESSDA Vocabularies Service."
    },
    "creators": {
      "type": "object",
      "description": "A Collection of Creators(affiliation) eg \"Ami Doe(University of DV)\". Potentially in many translated languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A Collection of Creators(affiliation) translated in this language",
          "items": [
            {
              "type": "object",
              "description": "A Creator instance.",
              "properties": {
                "name": {
                  "type": "string"
                },
                "affiliation": {
                  "type": "string"
                },
                "identifiers": {
                  "type": "array",
                  "description": "A collection of unique identifiers for a creator (e.g. ORCID)",
                  "items": [
                    {
                      "type": "object",
                      "description": "A unique identifier for a creator (e.g. ORCID, ROR etc.)",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "uri": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  ],
                  "additionalProperties": false
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccess": {
      "type": "string",
      "description": "Data Access preferably as Open or Restricted, either according to CV values or mapped from free text values. Will be Uncategorized if it would be empty otherwise."
    },
    "dataAccessFreeTexts": {
      "type": "object",
      "description": "A Collection of Data Access Free Texts descriptions for data collection, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "string",
              "description": "A Data Access Free Texts description for data collection.",
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccessUrl": {
      "type": "object",
      "description": "A URL where a user can navigate to access the data behind this study.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string"
        }
      }
    },
    "dataCollectionFreeTexts": {
      "type": "object",
      "description": "A collection of data collection FreeTexts Dates, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A collection data collection FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A data Collection FreeTexts instance",
              "properties": {
                "dataCollectionFreeText": {
                  "type": "string"
                },
                "event": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataCollectionPeriodEnddate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionPeriodStartdate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionYear": {
      "type": "integer",
      "description": "A JSON date year string, e.g. 2012."
    },
    "dataKindFreeTexts": {
      "type": "object",
      "description": "A collection of Data Kind FreeTexts, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection Data Kind FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A Data Kind FreeTexts instance",
              "properties": {
                "dataKindFreeText": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "fileLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A CMMStudy File Language (standardised ISO)."
      },
      "description": "An array of File Languages (standardised ISO) for this CMMStudy."
    },
    "funding": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of funding formation for this CMMStudy in this given ISO language code",
          "items": [
            {
              "type": "object",
              "description": "CMMStudy Funding Information",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "grantNumber": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "generalDataFormats": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of General Data Formats for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "General Data Formats for this CMMStudy in potentially multiple languages."
    },
    "isActive": {
      "type": "boolean",
      "description": "Is the record marked as deleted. If record is deleted this = false.",
      "default": true
    },
    "keywords": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Keywords for this CMMStudy in this Given iso Language code",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy keyword.",
              "properties": {
                "vocab": {
                  "type": "string"
                },
                "vocabUri": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "term": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Keywords for this CMMStudy in potentially multiple languages."
    },
    "langAvailableIn": {
      "type": "array"
    },
    "lastModified": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z.",
      "format": "date-time"
    },
    "oaiIdentifier": {
      "type": "string",
      "description": "The OAI identifier that is returned by the OAI-PMH repository."
    },
    "pidStudies": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "An array of Persistent Identifiers for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Persistent Identifier.",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "pid": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Persistent Identifiers for this CMMStudy in potentially multiple languages."
    },
    "publicationYear": {
      "type": "string",
      "description": "Year of publication (by publisher) of the study (for citation) - [YYYY] or the whole [YYYY-MM-DD]."
    },
    "publisher": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A CMMStudy institution publishing the research data for the given language code.",
          "properties": {
            "abbr": {
              "type": "string"
            },
            "publisher": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "recordType": {
      "type": "string",
      "description": "The type of record, i.e.'CMMStudy'.",
      "enum": [
        "CMMStudy"
      ]
    },
    "relatedPublications": {
      "type": "object",
      "description": "Related publications to this study. This may be present in multiple languages.",
      "patternProperties": {
        "[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "A related publications object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "The title of the related publication"
                },
                "holdings": {
                  "type": "array",
                  "description": "The URIs of the holdings of the related publication.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    "repositoryUrl": {
      "type": "string",
      "description": "The URL of the repository as defined in the repository's configuration"
    },
    "series": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "Series / study group that the study belongs to.",
              "properties": {
                "names": {
                  "type": "array",
                  "description": "An array of names of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "descriptions": {
                  "type": "array",
                  "description": "An array of descriptions of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "uris": {
                  "type": "array",
                  "description": "An array of URIs to the series / study group description page in the SPs web page.",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "studyAreaCountries": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Countries for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Country.",
              "properties": {
                "abbr": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "searchField": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Countries for this CMMStudy in potentially multiple languages."
    },
    "studyNumber": {
      "type": "string",
      "description": "A studyNumber that uniquely identifies the CMMStudy within the datacatalogue."
    },
    "studyUrl": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "string",
          "description": "A CMMStudy study Url for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing CmmStudy Urls in various languages."
    },
    "studyXmlSourceUrl": {
      "type": "string",
      "description": "The Study's Full xml URL of the Service Provider's endpoint"
    },
    "titleStudy": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy studyTitle for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "typeOfModeOfCollections": {
      "type": "object",
      "description": "A collection of description of the methods of data collection in Potentially many languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection of description of methods for this given language",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfSamplingProcedures": {
      "type": "object",
      "description": "Sampling procedures used for data collection.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfTimeMethods": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of timeDimensions for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Time Methods for this CMMStudy in potentially multiple languages."
    },
    "unitTypes": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Analysis Units for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Analysis Units for this CMMStudy in potentially multiple languages."
    },
    "universe": {
      "type": "object",
      "description": "The universes that the study belongs to. This may be present in multiple languages.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A universe instance.",
          "properties": {
            "inclusion": {
              "description": "The included group of this universe.",
              "type": "string"
            },
            "exclusion": {
              "type": "string",
              "description": "The excluded group of this universe."
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
}

=== cessda/cessda.cdc.osmh-indexer.cmm/src/test/resources/json/synthetic_compliant_record_nesstar.json
{
  "pidStudies": {
    "*": [
      {
        "pid": "\nch.sidos.ddi.468.7773\n"
      }
    ]
  },
  "keywords": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Médias et confiance",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Politique",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Immigration",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Bien-être subjectif",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Religion",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Exclusion sociale",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Santé et soins",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Moralité économique",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Démographie",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Famille et bien-être",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Valeurs",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Identification",
        "id": ""
      },
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Participation",
        "id": ""
      }
    ]
  },
  "dataCollectionPeriodStartdate": "2004-09-16",
  "dataCollectionYear": 2004,
  "dataAccessUrl": {},
  "typeOfTimeMethods": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Enquête transversale",
        "id": ""
      }
    ]
  },
  "creators": {
    "*": [
      {
        "name": "Joye, Dominique (resp.)",
        "affiliation": "Service suisse d'information et d'archivage de données pour les sciences sociales - SIDOS"
      },
      {
        "name": "Schöbi, Nicole",
        "affiliation": "Service suisse d'information et d'archivage de données pour les sciences sociales - SIDOS"
      },
      {
        "name": "Kaenel, Céline",
        "affiliation": "Service suisse d'information et d'archivage de données pour les sciences sociales - SIDOS"
      }
    ]
  },
  "abstract": {
    "xy": "L'enquête \"European Social Survey\" (ESS, http://www.europeansocialsurvey.org) est une nouvelle enquête destinée à mesurer les attitudes et croyances des populations européennes et à expliquer les réactions aux changements des institutions en Europe. Pourquoi une nouvelle enquête ? D'abord pour attaquer des problématiques qui sont au coeur des préoccupations des chercheurs aujourd'hui. Par exemple, qu'est-ce que la citoyenneté aujourd'hui ? Comment les différents pays européens vivent-ils les questions posées par l'immigration ?\nCette enquête est aussi nouvelle  car elle vise des standards de qualité très élevés, et impose donc de nombreuses et sévères conditions méthodologiques, de telle sorte que les données soient vraiment comparables entre les pays. Plus de 20 pays ont participé à la deuxième édition qui s'est déroulée en automne 2004. La prochaine édition aura lieu en 2006, puisqu'il est prévu de réaliser une enquête ESS toutes les deux années.\n\nLa deuxième enquête ESS en Suisse fut réalisée par l'institut MIS Trend, mandaté par l'archive suisse pour les sciences sociales, le SIDOS (actuellement FORS : http://forscenter.ch/fr/ ). Le terrain s'est terminé fin février 2005, avec plus de 2000 personnes interrogées en Suisse."
  },
  "series": {
    "xy": [
      {
        "names": ["European Social Survey"],
        "descriptions": [],
        "uris": []
      }
    ]
  },
  "studyAreaCountries": {
    "xy": [
      {
        "country": "Suisse",
        "abbr": "CH"
      }
    ]
  },
  "dataCollectionFreeTexts": {
    "*": [
      {
        "dataCollectionFreeText": "start",
        "event": "start"
      },
      {
        "dataCollectionFreeText": "end",
        "event": "end"
      },
      {
        "dataCollectionFreeText": "No date"
      }
    ]
  },
  "dataAccess": "Uncategorized",
  "dataAccessFreeTexts": {
    "xy": [
      "Aucune"
    ]
  },
  "classifications": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Médias, confiance, politique, immigration, bien-être subjectif, religion, exclusion sociale, santé et soins, moralité économique, démographie, famille, valeurs, identification, participation",
        "id": ""
      }
    ]
  },
  "titleStudy": {
    "xy": "European Social Survey in Switzerland - 2004"
  },
  "unitTypes": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Individu",
        "id": ""
      }
    ]
  },
  "dataCollectionPeriodEnddate": "2005-02-28",
  "publisher": {
    "xy": {
      "publisher": "Data and Research Information Services",
      "abbr": "DARIS"
    }
  },
  "publicationYear": "2007",
  "lastModified": "2015-05-04T22:55:30+0000",
  "studyUrl": {
    "*": "http://forscenter.ch/fr/service-de-donnees-et-d-information-sur-la-recherche/"
  },
  "studyNumber": "http://fors-getdata.unil.ch:80/obj/fStudy/ch.sidos.ddi.468.7773",
  "typeOfModeOfCollections": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Entretien téléphonique",
        "id": ""
      }
    ]
  },
  "fileLanguages": [],
  "funding": {},
  "typeOfSamplingProcedures": {
    "xy": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Sélection aléatoire à 3 phases:\n1) Tirage aléatoire de Sample points: 222 Sample Points ont été tirés aléatoirement après qu'ils aient été stratifiés selon les six régions suivantes:\n- Région lémanique (VD, VS, GE)\n- Espace Mittelland (BE, FR, SO, NE, JU)\n- Nordschweiz (ZH, BS, BL, AG)\n- Ostschweiz (GL, SH, AR, AI, SG, GR, TG)\n- Zentralschweiz (LU, UR, SZ, OW, NW, ZG)\n- Ticino (TI)\n2) Sélection aléatoire des ménages à partir du registre téléphonique;\n3) Tirage de la personne-cible au moyen de la méthode KISH.",
        "id": ""
      }
    ]
  },
  "universe": {
    "xy": {
      "inclusion": "Population suisse âgée de 15 ans et plus parlant allemand, français ou italien."
    }
  },
  "dataKindFreeTexts": {
    "xy": [
      {
        "dataKindFreeText": "Données quantitatives"
      }
    ]
  },
  "generalDataFormats": {},
  "relatedPublications": {},
  "repositoryUrl": "http://fors-getdata.unil.ch/",
  "studyXmlSourceUrl": "https://oai-pmh.nsd.no/oai-pmh?verb=GetRecord&identifier=http%3A%2F%2Ffors-getdata.unil.ch%3A80%2Fobj%2FfStudy%2Fch.sidos.ddi.468.7773&metadataPrefix=oai_ddi"
}
