=== cessda/cessda.cdc.osmh-indexer.cmm/src/main/resources/json/schema/CMMStudy.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$defs":  {
    "vocabAttributes": {
      "type": "object",
      "description": "A term in a controlled vocabulary.",
      "properties": {
        "vocab": {
          "type": "string",
          "description": "The name of the controlled vocabulary."
        },
        "vocabUri": {
          "type": "string",
          "description": "The URI of the controlled vocabulary."
        },
        "id": {
          "type": "string",
          "description": "The ID of the item in the controlled vocabulary."
        },
        "term": {
          "type": "string",
          "description": "The term being referenced."
        }
      },
      "additionalProperties": false
    }
  },
  "title": "CMMStudy",
  "description": "This schema defines the format of the CMMStudy record type.",
  "type": "object",
  "required": [
    "studyNumber"
  ],
  "additionalProperties": false,
  "properties": {
    "abstract": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy abstract for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing an abstract in various languages. Uses language code properties and abstract values. E.g. {'en': 'An abstract', 'no': 'Et sammendrag'}"
    },
    "accessClass": {
      "type": "string",
      "description": "Class of availability of the research data."
    },
    "associatedInstitutions": {
      "type": "array",
      "description": "An array of Associated Institutions for this CMMStudy.",
      "items": {
        "type": "string",
        "description": "A CMMStudy Associated Institution ."
      }
    },
    "classIdentifier": {
      "type": "string",
      "description": "Unique identifier of class/category within the classification system."
    },
    "classifications": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Topics(classifications) for this CMMStudy in potentially multiple languages."
    },
    "code": {
      "type": "string",
      "description": "The short name of the repository as defined in the CESSDA Vocabularies Service."
    },
    "creators": {
      "type": "object",
      "description": "A Collection of Creators(affiliation) eg \"Ami Doe(University of DV)\". Potentially in many translated languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A Collection of Creators(affiliation) translated in this language",
          "items": [
            {
              "type": "object",
              "description": "A Creator instance.",
              "properties": {
                "name": {
                  "type": "string"
                },
                "affiliation": {
                  "type": "string"
                },
                "identifiers": {
                  "type": "array",
                  "description": "A collection of unique identifiers for a creator (e.g. ORCID)",
                  "items": [
                    {
                      "type": "object",
                      "description": "A unique identifier for a creator (e.g. ORCID, ROR etc.)",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "uri": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  ],
                  "additionalProperties": false
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccess": {
      "type": "string",
      "description": "Data Access preferably as Open or Restricted, either according to CV values or mapped from free text values. Will be Uncategorized if it would be empty otherwise."
    },
    "dataAccessFreeTexts": {
      "type": "object",
      "description": "A Collection of Data Access Free Texts descriptions for data collection, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "string",
              "description": "A Data Access Free Texts description for data collection.",
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataAccessUrl": {
      "type": "object",
      "description": "A URL where a user can navigate to access the data behind this study.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string"
        }
      }
    },
    "dataCollectionFreeTexts": {
      "type": "object",
      "description": "A collection of data collection FreeTexts Dates, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "A collection data collection FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A data Collection FreeTexts instance",
              "properties": {
                "dataCollectionFreeText": {
                  "type": "string"
                },
                "event": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "dataCollectionPeriodEnddate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionPeriodStartdate": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z. In future restrict to [\"format\": \"date-time\" or \"date\"]"
    },
    "dataCollectionYear": {
      "type": "integer",
      "description": "A JSON date year string, e.g. 2012."
    },
    "dataKindFreeTexts": {
      "type": "object",
      "description": "A collection of Data Kind FreeTexts, potentially translated in multiple languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection Data Kind FreeTexts for this given language",
          "items": [
            {
              "type": "object",
              "description": "A Data Kind FreeTexts instance",
              "properties": {
                "dataKindFreeText": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "fileLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A CMMStudy File Language (standardised ISO)."
      },
      "description": "An array of File Languages (standardised ISO) for this CMMStudy."
    },
    "funding": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of funding formation for this CMMStudy in this given ISO language code",
          "items": [
            {
              "type": "object",
              "description": "CMMStudy Funding Information",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "grantNumber": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "generalDataFormats": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of General Data Formats for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "General Data Formats for this CMMStudy in potentially multiple languages."
    },
    "isActive": {
      "type": "boolean",
      "description": "Is the record marked as deleted. If record is deleted this = false.",
      "default": true
    },
    "keywords": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Keywords for this CMMStudy in this Given iso Language code",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy keyword.",
              "properties": {
                "vocab": {
                  "type": "string"
                },
                "vocabUri": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "term": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Keywords for this CMMStudy in potentially multiple languages."
    },
    "langAvailableIn": {
      "type": "array"
    },
    "lastModified": {
      "type": "string",
      "description": "A JSON date string in ISO 8601 format, e.g. 2012-04-23T18:25:43.511Z.",
      "format": "date-time"
    },
    "oaiIdentifier": {
      "type": "string",
      "description": "The OAI identifier that is returned by the OAI-PMH repository."
    },
    "pidStudies": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "array",
          "description": "An array of Persistent Identifiers for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Persistent Identifier.",
              "properties": {
                "agency": {
                  "type": "string"
                },
                "pid": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Persistent Identifiers for this CMMStudy in potentially multiple languages."
    },
    "publicationYear": {
      "type": "string",
      "description": "Year of publication (by publisher) of the study (for citation) - [YYYY] or the whole [YYYY-MM-DD]."
    },
    "publisher": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A CMMStudy institution publishing the research data for the given language code.",
          "properties": {
            "abbr": {
              "type": "string"
            },
            "publisher": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "recordType": {
      "type": "string",
      "description": "The type of record, i.e.'CMMStudy'.",
      "enum": [
        "CMMStudy"
      ]
    },
    "relatedPublications": {
      "type": "object",
      "description": "Related publications to this study. This may be present in multiple languages.",
      "patternProperties": {
        "[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "A related publications object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "The title of the related publication"
                },
                "holdings": {
                  "type": "array",
                  "description": "The URIs of the holdings of the related publication.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    "repositoryUrl": {
      "type": "string",
      "description": "The URL of the repository as defined in the repository's configuration"
    },
    "series": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "description": "Series / study group that the study belongs to.",
              "properties": {
                "names": {
                  "type": "array",
                  "description": "An array of names of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "descriptions": {
                  "type": "array",
                  "description": "An array of descriptions of the series / study group.",
                  "items": {
                    "type": "string"
                  }
                },
                "uris": {
                  "type": "array",
                  "description": "An array of URIs to the series / study group description page in the SPs web page.",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "studyAreaCountries": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Countries for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "type": "object",
              "description": "A CMMStudy Country.",
              "properties": {
                "abbr": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "searchField": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Countries for this CMMStudy in potentially multiple languages."
    },
    "studyNumber": {
      "type": "string",
      "description": "A studyNumber that uniquely identifies the CMMStudy within the datacatalogue."
    },
    "studyUrl": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}|\\*$": {
          "type": "string",
          "description": "A CMMStudy study Url for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing CmmStudy Urls in various languages."
    },
    "studyXmlSourceUrl": {
      "type": "string",
      "description": "The Study's Full xml URL of the Service Provider's endpoint"
    },
    "titleStudy": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "string",
          "description": "A CMMStudy studyTitle for the given language code."
        }
      },
      "additionalProperties": false,
      "description": "An object containing Study Titles in various languages. Uses language code properties and abstract values. E.g. {'en': 'An studyTitle', 'no': 'Et studyTitle'}."
    },
    "typeOfModeOfCollections": {
      "type": "object",
      "description": "A collection of description of the methods of data collection in Potentially many languages",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "A collection of description of methods for this given language",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfSamplingProcedures": {
      "type": "object",
      "description": "Sampling procedures used for data collection.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "typeOfTimeMethods": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of timeDimensions for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Time Methods for this CMMStudy in potentially multiple languages."
    },
    "unitTypes": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "array",
          "description": "An array of Analysis Units for this CMMStudy in this Given iso Language code.",
          "items": [
            {
              "$ref": "#/$defs/vocabAttributes"
            }
          ]
        }
      },
      "additionalProperties": false,
      "description": "Analysis Units for this CMMStudy in potentially multiple languages."
    },
    "universe": {
      "type": "object",
      "description": "The universes that the study belongs to. This may be present in multiple languages.",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "description": "A universe instance.",
          "properties": {
            "inclusion": {
              "description": "The included group of this universe.",
              "type": "string"
            },
            "exclusion": {
              "type": "string",
              "description": "The excluded group of this universe."
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
}

=== cessda/cessda.cdc.osmh-indexer.cmm/src/test/resources/json/synthetic_compliant_record_ddi_3.json
{
  "abstract": {
    "en": "Attitude of the political leadership (members of parliament) in the USA to other nations and problems in world politics.",
    "de": "Einstellung der politischen Führungsschicht (Parlamentsmitglieder) in den USA zu anderen Nationen und weltpolitischen Problemen."
  },
  "classifications": {
    "de": [
      {
        "vocabUri": "",
        "vocab": "ZA-Kategorien",
        "term": "Politische Fragen (Issues)",
        "id": ""
      },
      {
        "vocabUri": "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2.2",
        "vocab": "CESSDA Topic Classification",
        "term": "Internationale Politik und Internationale Organisationen",
        "id": ""
      },
      {
        "vocabUri": "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2.2",
        "vocab": "CESSDA Topic Classification",
        "term": "Konflikte, Sicherheit und Frieden",
        "id": ""
      }
    ],
    "en": [
      {
        "vocabUri": "",
        "vocab": "ZA-Categories",
        "term": "Political Issues",
        "id": ""
      },
      {
        "vocabUri": "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2.2",
        "vocab": "CESSDA Topic Classification",
        "term": "International politics and organisations",
        "id": ""
      },
      {
        "vocabUri": "https://vocabularies.cessda.eu/urn/urn:ddi:int.cessda.cv:TopicClassification:4.2.2",
        "vocab": "CESSDA Topic Classification",
        "term": "Conflict, security and peace",
        "id": ""
      }
    ]
  },
  "creators": {
    "en": [
      {
        "name": "Synthetic ORCID",
        "identifiers": [{
          "id": "0000-0000-0000-0000",
          "type": "ORCID",
          "uri": "https://orcid.org/0000-0000-0000-0000",
          "role": "pid"
        }]
      }
    ],
    "de": [
      {
        "name": "Synthetic ORCID de",
        "identifiers": [{
          "id": "0000-0000-0000-0000",
          "type": "ORCID",
          "uri": "https://orcid.org/0000-0000-0000-0000",
          "role": "pid"
        }]
      }
    ]
  },
  "dataAccess": "Open",
  "dataAccessFreeTexts": {
    "en": [
      "Data and documents are only released for academic research and teaching after the data depositor's written authorization."
    ],
    "de": [
      "Daten und Dokumente sind für die akademische Forschung und Lehre nur nach schriftlicher Genehmigung des Datengebers zugänglich."
    ]
  },
  "dataAccessUrl": {
  },
  "dataCollectionFreeTexts": {
  },
  "dataCollectionYear": 1958,
  "dataCollectionPeriodEnddate": "1958-04",
  "dataCollectionPeriodStartdate": "1958-02",
  "dataKindFreeTexts": {
    "en": [
      {
        "dataKindFreeText": "Numeric",
        "type": "Quantitative"
      }
    ]
  },
  "fileLanguages":[
    "de",
    "en"
  ],
  "funding": {
    "en": [
      {
        "agency": "GESIS - Leibniz Institute for the Social Sciences",
        "grantNumber": "Grant Number"
      }
    ],
    "de": [
      {
        "agency": "GESIS - Leibniz Institut für Sozialwissenschaften",
        "grantNumber": "Grant Number"
      }
    ]
  },
  "generalDataFormats": {},
  "keywords": {
    "en": [
      {
        "vocabUri": "https://elsst.cessda.eu/id/",
        "vocab": "ELSST",
        "term": "POLITICAL ISSUES",
        "id": ""
      }
    ]
  },
  "lastModified": "2023-12-06T13:30:08.8725293Z",
  "pidStudies": {
    "*": [
      {
        "agency": "DOI",
        "pid": "doi:10.4232/1.0004"
      }
    ]
  },
  "publisher": {
    "en": {
      "abbr": "GESIS",
      "publisher": "GESIS - Leibniz Institute for the Social Sciences"
    },
    "de": {
      "abbr": "",
      "publisher": "GESIS - Leibniz Institut für Sozialwissenschaften"
    }
  },
  "publicationYear": "1964",
  "relatedPublications": {
    "en": [{
      "title": "Synthetic Publication 1",
      "holdings": [
        "https://doi.org/10.4232/00000",
        "doi:10.4232/00000"
      ],
      "publicationDate": "2025"
     }
    ],
    "de": [{
      "title": "Synthetische Publikation 1",
      "holdings": [
        "https://doi.org/10.4232/00000",
        "doi:10.4232/00000"
      ],
      "publicationDate": "2025"
    }]
  },
  "repositoryUrl": "http://dbkapps.gesis.org/dbkoai/oai.asp",
  "series": {
    "de": [
      {
        "names": ["Ausgedachter Serienname"],
        "descriptions": ["Dies ist ein Beispiel für eine Serienbeschreibung. Diese erfundene Serie wurde über mehrere erfundene Jahrzehnte hinweg gesammelt."],
        "uris": ["https://example.com/series", "https://example.com/seriesaltlink"]
      }
    ],
    "en": [
      {
        "names": ["Made up series name", "Has second made up name in English"],
        "descriptions": ["This is an example of series description. This made up series has been collected over several made-up decades."],
        "uris": ["https://example.com/series", "https://example.com/seriesaltlink"]
      },
      {
        "names": ["Simple second series test"],
        "descriptions": [],
        "uris": []
      }
    ]
  },
  "studyAreaCountries": {
    "de": [{
      "abbr": "US",
      "country": "Vereinigte Staaten von Amerika"
    }],
    "en": [{
      "abbr": "US",
      "country": "United States of America"
    }]
  },
  "studyNumber": "oai:dbk.gesis.org:DBK/ZA0004",
  "studyUrl": {
  },
  "studyXmlSourceUrl": "https://oai.ukdataservice.ac.uk:8443/oai/provider?verb=GetRecord&identifier=oai%3Adbk.gesis.org%3ADBK%2FZA0004&metadataPrefix=ddi",
  "titleStudy": {
    "en": "International Outlooks of Political Leaders (USA)",
    "de": "International Outlooks of Political Leaders (USA)"
  },
  "typeOfModeOfCollections": {
    "en": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Oral survey with standardized questionnaire",
        "id": ""
      }
    ],
    "de": [
      {
        "vocabUri": "",
        "vocab": "",
        "term": "Mündliche Befragung mit standardisiertem Fragebogen",
        "id": ""
      }
    ]
  },
  "typeOfSamplingProcedures": {
    "en": [
      {
        "vocabUri": "urn:ddi:int.ddi.cv:SamplingProcedure:1.1.4",
        "vocab": "",
        "term": "Quota sample",
        "id": ""
      }
    ],
    "de": [
      {
        "vocabUri": "urn:ddi:int.ddi.cv:SamplingProcedure:1.1.4",
        "vocab": "",
        "term": "Quotenauswahl",
        "id": ""
      }
    ]
  },
  "typeOfTimeMethods": {
    "en": [
      {
        "vocabUri": "urn:ddi:int.ddi.cv:TimeMethod:1.2.3",
        "vocab": "TimeMethod",
        "term": "Longitudinal",
        "id": ""
      }
    ]
  },
  "unitTypes": {
    "en": [{
      "vocabUri": "urn:ddi:int.ddi.cv:AnalysisUnit:2.1.3",
      "vocab": "AnalysisUnit",
      "term": "Individual",
      "id": ""
    }]
  },
  "universe": {
    "de": {
      "inclusion": "Kongressmitglieder (Senat und Repräsentantenhaus)"
    },
    "en": {
      "inclusion": "Members of congress (Senate and House of Representatives)."
    }
  }
}
